version: '3'
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "laravel_app"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql
    volumes:
      - ./:/var/www

  redis:
    image: "redis:alpine"
    container_name: "laravel_redis"
    restart: unless-stopped

  mysql:
    image: mysql:8
    container_name: "laravel_mysql"
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Pc4hzz.sf
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "laravel_phpmyadmin"
    restart: unless-stopped
    environment:
      - PMA_HOST=mysql
    depends_on:
      - mysql
    ports:
      - "8008:80"

volumes:
  db_data:
    driver: local