version: '3'
services:

  web:
    build:
      context: ./
      dockerfile: Dockerfile
    image: "zhoulei0406/laravelapp:8"
    container_name: "laravel_web"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - redis
      - mysql
    links:
      - redis
      - mysql
    volumes:
      - "/home/laravel/storage:/var/www/html/storage"
      - "/etc/localtime:/etc/localtime"
    networks:
      - laravel

  redis:
    image: "redis:alpine"
    container_name: "laravel_redis"
    restart: unless-stopped
    volumes:
      - "/home/laravel/redis:/data"
      - "/etc/localtime:/etc/localtime"
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: "laravel_mysql"
    security_opt:
      - seccomp:unconfined
    restart: unless-stopped
    volumes:
      - "/home/laravel/mysql:/var/lib/mysql"
      - "/etc/localtime:/etc/localtime"
    environment:
      MYSQL_ROOT_PASSWORD: Pc4hzz.sf
    ports:
      - "3306:3306"
    networks:
      - laravel

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: "laravel_phpmyadmin"
    restart: unless-stopped
    volumes:
      - "/etc/localtime:/etc/localtime"
    environment:
      - PMA_HOST=mysql
      - PMA_ABSOLUTE_URI=https://www.zuogechengxu.com/pma/
    depends_on:
      - mysql
    ports:
      - "8008:80"
    networks:
      - laravel

networks:
  laravel:
    driver: bridge
