name: Docker Image CI Master

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Upload to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
            DEPLOY_KEY: ${{ secrets.SERVER_SECRET }}
            ARGS: -avz docker-compose.yml --delete
            SERVER_PORT: 22
            FOLDER: ./
            SERVER_IP: ${{ secrets.SERVER_HOST }}
            USERNAME: ${{ secrets.SERVER_USERNAME }}
            SERVER_DESTINATION: abc


